# -*- coding: utf-8 -*-
"""lab4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tdWoY0cBiqEVobSRMEYazRnBYvj55pTX
"""

students= {}

def add_student(name,grades):
  name=name.lower()
  if name in students:
    print(f"{name.capitalize()} already exists.Updating the grades instead.")
    update_grades(name,grades)
  else:
    students[name]=grades

    print(f"{name.capitalize()} added successfully.")

def update_grades(name, grades):

    name = name.lower()
    if name in students:
        students[name].extend(grades)
    else:
        print(f"Student {name.capitalize()} does not exist. Adding as a new student.")
        add_student(name, grades)

def calculate_average(name):

    name = name.lower()
    if name in students:
        grades = students[name]
        return sum(grades) / len(grades)
    else:
        print(f"Student {name.capitalize()} does not exist.")
        return None

def print_students_with_averages():

    for name, grades in students.items():
        avg_grade = calculate_average(name)
        print(f"{name.capitalize()} - Average: {avg_grade:.2f}")

def sort_students_by_average():
    # Sort students by their average grades in descending order without using inbuilt sort function
    sorted_students = []
    for student in students:
        avg_grade = calculate_average(student)
        sorted_students.append((student, avg_grade))

    # Manual sorting in descending order based on average grades
    for i in range(len(sorted_students)):
        for j in range(i + 1, len(sorted_students)):
            if sorted_students[i][1] < sorted_students[j][1]:
                sorted_students[i], sorted_students[j] = sorted_students[j], sorted_students[i]


    return sorted_students

sorted_students = sort_students_by_average()



for student, avg in sorted_students:
        print(f"{student.capitalize()} - Average: {avg:.2f}")

add_student('Anmol', [85, 90, 88])
add_student('Naresh', [78, 81, 85])
add_student('Neha', [92, 87, 90])

print("Students with their average grades:")
print_students_with_averages()

print("Students with their average grades:")
print_students_with_averages()

print("\nStudents sorted by their average grades in descending order:")
sort_students_by_average()